features:
  ghastDropChanges:
    enabled: true
    whitelist: false
    worlds: world_names_to_drop_tears_in
  regenChanges: true
  playerListHealth:
    colours: true
    enabled: true
    delay: 10
    belowName: true
    scaling: 5
    roundHealth: false
    belowNameUnit: "&4&h"
  recipeChanges:
    enabled: true
  noEnderpearlDamage: true
  headDrop:
    enabled: true
    pvp:
      pvponly: false
      nonteamonly: true
    percentChance: 100
    onStake: true
  deathLightning: false
  deathMessages:
    enabled: false
    message: "&c%message at %coords"
    remove: false
  deathDrops:
    enabled: false
    items:
      template1:
        group: group1
        id: 3
        amount: 1-3
        chance: 0
      template2:
        group: group1
        id: "35:7"
        amount: 1-64
        chance: 0
      template3:
        group: group2
        id: 48
        amount: 20-30
        chance: 0
  anonChat:
    enabled: true
  goldenHeads:
    enabled: true
    amountExtra: 4
  hardcoreHearts:
    enabled: true
  footprints:
    enabled: true
    renderdistance: 60
    mindistance: 2
    time: 120
  potionNerfs:
    disableSplash: true
    disableAbsorb: true
    disableGlowstone: true
  deathbans:
    enabled: false
    delay: 10
    bans:
      example1:
        duration: "2h"
        message: "You are under a death ban, you will be unbanned in %timeleft"
      opban:
        duration: "0s"
        message: "doesn't matter since 0, will never be applied"
freeze:
  delay: 40
  time: 160
  effects:
  - "11:5"
  - "4:5"
  - "2:5"
  - "14:1"
  - "15:5"
scatter:
  maxtries: 250
  maxattempts: 3
  delay: 60
  allowedBlocks:
  - 1
  - 2
  - 3
  - 12
  - 13
  - 78
  - 79
  default:
    world: world
    x: 0
    z: 0
    radius: 1000
    minradius: 50
    players: "*"
    type: RandomCircle
    useteams: yes
border:
  id: 7
  meta: 0