name: UltraHardcore
main: com.publicuhc.ultrahardcore.UltraHardcore
version: ${git.commit.id.describe}
description: Make minecraft harder, no health regen and extras!
author: ghowden/Eluinhost
website: wiki.publicuhc.com
database: false
softdepend: [ProtocolLib]
commands:
    heal:
      description: Heal a player/yourself
      usage: /<command> [player/*]
      aliases: [uhcheal]
    healself:
      description: Heal yourself
      usage: /<command>
      aliases: [uhchealself]
    feed:
      description: Feed yourself
      usage: /<command> [player/*]
      aliases: [uhcfeed]
    feedself:
      description: Feed yourself
    feature:
      description: Allows turning on/off of features and seeing the feature list
      usage: /<command> toggle featureID OR /<command> list
      aliases: [uhcfeature]
    freeze:
      description: Freezes players
      usage: /<command> player/*
      aliases: [uhcfreeze]
    unfreeze:
      description: Unfreezes players
      usage: /<command> player/*
      aliases: [uhcunfreeze]
    tpp:
      description: Teleports all players to another player/location
      usage: /<command> list_of_players/* playername OR /tpp list_of_players/* x,y,z[,worldname]
      aliases: [uhctpp]
    ci:
      description: Clears a player/s inventory
      usage: /<command> [list of space separated names/*]
      aliases: [uhcci]
    ciself:
      description: Clears your inventory
      usage: /ciself
      aliases: [uhcciself]
    whitelistall:
      description: Whitelist all online players
      usage: /<command>
      aliases: [uhcwhitelistall]
permissions:
    UHC.heal.*:
        description: Gives all heal permissions
        default: op
        children:
          UHC.heal.self: true
          UHC.heal.other: true
          UHC.heal.announce: true
    UHC.feed.*:
        description: Gives all feed permissions
        default: op
        children:
          UHC.feed.self: true
          UHC.feed.other: true
          UHC.feed.announce: true
    UHC.ci.*:
        description: Gives all clear inventory commands
        default: op
        children:
          UHC.ci.self: true
          UHC.ci.other: true
    UHC.ci.self:
        description: Clear your own inventory
        default: op
    UHC.ci.other:
        description: Clear someone elses inventory
        default: op
    UHC.ci.immune:
        description: Immune to inventory clears
        default: false
    UHC.clear.announce:
        description: All ci commands will be announced to this player
        default: false
    UHC.heal.self:
        description: Fully heal yourself
        default: false
    UHC.heal.other:
        description: Fully heal another player
        default: false
    UHC.heal.announce:
        description: All heal commands will be announced to this player
        default: false
    UHC.feed.self:
        description: Fully feeds yourself
        default: false
    UHC.feed.other:
        description: Fully feed another player
        default: false
    UHC.feed.announce:
        description: All feed commands will be announced to this player
        default: false
    UHC.feature.toggle:
        description: Allows a player to globally change loaded features
        default: op
    UHC.feature.list:
        description: Allows a player to see a list of loaded features and their state
        default: true
    UHC.freeze.command:
        description: Allows a player to use the /freeze command to freeze everyone
        default: op
    UHC.freeze.antifreeze:
        description: Players with this permission are not affected by /freeze
        default: op
    UHC.playerListHealth:
        description: Player with this permission have health on their name in the player list
        default: true
    UHC.recipes.disableGMelon:
        description: Player with this permission cannot craft normal glistering melons
        default: true
    UHC.recipes.disableGCarrot:
        description: Player with this permission cannot craft normal golden carrot
        default: true
    UHC.recipes.allowNewGCarrot:
        description: Player with this permission can craft the new golden carrot recipe
        default: true
    UHC.recipes.allowNewGMelon:
        description: Player with this permission can craft the new glistering melon recipe
        default: true
    UHC.recipes.allowNotchApple:
        description: Player with this permission can craft the notch golden apple
        default: false
    UHC.disableRegen:
        description: player with this permission will have regen disabled at full hunger
        default: true
    UHC.enderpearls.damage:
        description: Players with this permission take damage when teleporting using enderpearls with the feature enabled
        default: false
    UHC.tpall:
        description: Allows a player to tp all players to another player/location
        default: op
    UHC.nether.allow:
        description: Allows travel to the nether when feature is enabled
        default: op
    UHC.whitelistall:
        description: Allows use of the /whitelistall command
        default: op